name: posn

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - ipython=9.*
  - pytorch=2.*
  - numpy<2
  - hdf5
  - einops=0.8*
  - torchvision=0.*
  - lightning=2.*
  - torchmetrics=0.*
  - hydra-core=1.*
  - matplotlib=3.*
  - plotly=6.*
  - scikit-learn=1.6.*
  - scipy=1.*
  - scipy-stubs=1.15.2.2
  - tqdm=4.*

  # --- dev tools --
  - pre-commit=3.*
  - pytest=7.*
  - mypy
  - ruff

  # --- pip ---
  - pip>=23
  - pip:
      - einops
      - omegaconf
      - hydra-core
      - hydra-optuna-sweeper
      - hydra-colorlog
      - rootutils
